### ISSUE TITLE
Terminer le Powerpoint

### ISSUE THREAD

**Issue by Niluel** [Lacaravaneducodeur/Fashion-Game#11]

**Comment by lucnicolas** [comment]
Remarques :

- [ ] Renomer "L'équipe" en "Les Parties Prenantes"
- [ ] Commanditaire = PO
- [ ] Écrire la fonction en dessous des noms en light
- [ ] Écrire chiffres et infos clés dans le contexte
- [ ] Mission illisible avec le pied de page (mettre en colonne ?)
- [ ] Mettre le smart des objectifs correspondants à ceux-ci
- [ ] Diminuer la taille du pied de page !!
