### ISSUE TITLE
Premier jet d'un scénario

### ISSUE THREAD

**Issue by lucnicolas** [Lacaravaneducodeur/Fashion-Game#12]
Réaliser un premier jet pour le scénario du jeu

**Comment by lucnicolas** [comment]
Rédigé par @AlexisJAR : 
___

- **Cadre:** stage d’immersion dans une chaîne de mode (École? Pro?)

- Avec **deux équipes**: équipe créa, et équipe mode. Un représentant par équipe.

- Équipes demandent de l’aide pour finir un projet à temps.

- Choix de l’équipe à aider

- Une fois dans l’équipe, on découvre **tous les métiers à découvrir dans la branche** (créa ou prod).

- Puis équipe subdivisée selon spécifications, puis autres subdivisions jusqu’à **arriver au choix final**.

- Selon choix de type, un vêtement différent donné à la fin

- Sauf si, en créa, en tout début de chaîne, là, laisser choix du vêtement (enfin, si correspond aux métiers à représenter).

- Prendre plus d’infos sur les métiers en question afin de mieux développer les branches, en plaçant un «défi» le long de la route. (Défi qcm? Point n’ click? À déterminer)
___
- [ ] Faire la liste des 15 métiers, à associer à 15 personnages.

- [ ] Répartir les personnages aux métiers de manière à briser les idées reçues du type «femme/homme pas faire ça, ça pas féminin/masculin».

**Comment by lucnicolas** [comment]
**Liste des métiers de R&D/Création :** 

- Directeur(rice) Studio
- Designer Mode (Styliste)
- Responsable Bureau d'études

**Liste des métiers de production :** 

- Agent(e) de finition
- Contrôleur(se) Qualité
- Couturier(ère)
- Modéliste/Toiliste
- Premier(e) d'Atelier
- Repasseur(se)
- Agent(e) des Méthodes
- Coupeur(se)
- Couturier(ère) Mécanicien(ne) en confection
- Patronier(ère) Gradeur(se)
- Prototypiste
- Responsable d'atelier de production / Responsable de production

**Comment by AlexisJAR** [comment]
**Liste des personnages (provisoires, à discuter)**

**Métiers R&D/Création :**

- Directrice Studio : Elise (Personnage présent au premier choix, choix créa ou prod) 
- Designer Mode (styliste) : Cyril
- Responsable bureau d'étude: Jeanne

**Métiers de production :**

- Agent de finition : Elies
- Contrôleuse qualité : Lilas
- Couturier : Éric
- Modéliste/Toiliste: Marie
- Premier d'Atelier : Jean
- Repasseuse : Tina
- Agent des Méthodes : Samuel
- Coupeuse : Elena
- Couturier Mécanicien en confection : Franck
- Patronière Gradeuse : Valentine
- Prototypiste : Alaric
- Responsable d'atelier de production/Responsable de production : Angélique (Personnage présent au premier choix, choix créa ou prod)
