### ISSUE TITLE
CRR du 17 septembre 2019

### ISSUE THREAD

**Issue by Niluel** [Lacaravaneducodeur/Fashion-Game#3]
Faire compte rendu de réunion (nomenclature: 190916_PI_FashionGame_CRR)

**Comment by lucnicolas** [comment]
190917_PI_FashionGame_CRR - [190917_PI_FashionGame_CRR (1).docx](https://github.com/Lacaravaneducodeur/Fashion-Game/files/3646560/190917_PI_FashionGame_CRR.1.docx)
